In [93]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in c:\users\gxmar\appdata\roaming\python\python311\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gxmar\appdata\local\programs\python\python311\lib\site-packages (from requests->kagglehub) (2025.10.5)
Requirement already satisfied: colorama in c:\users\gxmar\appdata\roaming\python\python311\site-packages (from tqdm->kagglehub) (0.4.6)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [94]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("calvinrostanto/fantasy-premier-league-2025-2026")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\gxmar\.cache\kagglehub\datasets\calvinrostanto\fantasy-premier-league-2025-2026\versions\197

In [95]:
import pandas as pd

In [96]:
df = pd.read_csv(r"C:\Users\gxmar\.cache\kagglehub\datasets\calvinrostanto\fantasy-premier-league-2025-2026\versions\197\fpl_player_statistics.csv")

In [97]:
df

,player_name,club_name,position_name,now_cost,total_points,event_points,points_per_game,selected_by_percent,goals_scored,assists,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,Erling Haaland,Man City,FWD,14.8,193,0,7.1,65.2,22,7,...,1,1,22,5,1,1,1,1,1.05,0.40
1,Antoine Semenyo,Man City,MID,8.2,165,8,6.1,54.8,14,6,...,14,9,5,3,4,2,2,1,1.00,0.30
2,Bruno B.Fernandes,Man Utd,MID,9.9,158,13,6.3,38.6,7,13,...,5,3,4,2,3,1,5,2,1.04,0.17
3,Declan Rice,Arsenal,MID,7.5,157,5,5.6,32.4,4,9,...,22,15,18,8,7,5,9,3,1.01,0.45
4,Gabriel Gabriel,Arsenal,DEF,7.1,153,9,6.7,42.9,3,4,...,33,1,33,9,2,1,4,1,1.00,0.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,Jayce Fitzgerald,Man Utd,MID,4.3,0,0,0.0,0.0,0,0,...,611,357,558,189,657,251,603,230,0.00,0.00
815,Toby Collyer,Man Utd,MID,4.5,0,0,0.0,0.0,0,0,...,445,266,628,230,709,284,659,265,0.00,0.00
816,Pervis Estupiñan,Brighton,DEF,4.5,0,0,0.0,0.0,0,0,...,418,78,610,239,694,255,743,255,0.00,0.00
817,Tariq Lamptey,Brighton,DEF,4.4,0,0,0.0,0.1,0,0,...,532,111,574,235,669,254,512,183,0.00,0.00
818,Carlos Miguel C.Miguel,Nott'm Forest,GKP,4.0,0,0,0.0,0.1,0,0,...,688,56,471,66,596,75,547,76,0.00,0.00

In [98]:
sorted(df.columns.tolist())

['assists',
 'bonus',
 'clean_sheets',
 'clean_sheets_per_90',
 'clearances_blocks_interceptions',
 'club_name',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'creativity_rank',
 'creativity_rank_type',
 'defensive_contribution',
 'defensive_contribution_per_90',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'dreamteam_count',
 'event_points',
 'expected_assists',
 'expected_assists_per_90',
 'expected_goal_involvements',
 'expected_goal_involvements_per_90',
 'expected_goals',
 'expected_goals_conceded',
 'expected_goals_conceded_per_90',
 'expected_goals_per_90',
 'form',
 'form_rank',
 'form_rank_type',
 'goals_conceded',
 'goals_conceded_per_90',
 'goals_scored',
 'ict_index',
 'ict_index_rank',
 'ict_index_rank_type',
 'influence',
 'influence_rank',
 'influence_rank_type',
 'minutes',
 'news',
 'now_cost',
 'now_cost_rank',
 'now_cost_rank_type',
 'own_goals',
 'penalties_missed',
 'penalties_order',
 'penalties_saved',
 'penalties_text',
 'player_name',
 'points_per_game',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'position_name',
 'recoveries',
 'red_cards',
 'saves',
 'saves_per_90',
 'selected_by_percent',
 'selected_rank',
 'selected_rank_type',
 'starts',
 'starts_per_90',
 'tackles',
 'threat',
 'threat_rank',
 'threat_rank_type',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'yellow_cards']

In [99]:
df['goals_per_90'] = df['goals_scored'] / df['minutes'] * 90
df['assists_per_90'] = df['assists'] / df['minutes'] * 90
df['goal_involvements_per_90'] = df['goals_per_90'] + df['assists_per_90']

In [100]:
df['underperformance_index'] = df['expected_goal_involvements_per_90'] / df['goal_involvements_per_90']

In [101]:
df.query('underperformance_index != inf').sort_values(['underperformance_index'], ascending = False).head(10)

,player_name,club_name,position_name,now_cost,total_points,event_points,points_per_game,selected_by_percent,goals_scored,assists,...,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,goals_per_90,assists_per_90,goal_involvements_per_90,underperformance_index
255,Jhon J.Arias,Wolves,MID,4.9,45,0,2.0,0.1,1,0,...,332,144,433,145,1.13,0.16,0.080573,0.000000,0.080573,3.971556
18,James Tarkowski,Everton,DEF,5.7,121,3,4.3,10.7,0,1,...,42,19,30,10,1.00,0.32,0.000000,0.035714,0.035714,3.360000
168,Yéremy Yeremy,Crystal Palace,MID,5.8,65,1,2.5,0.2,2,1,...,278,119,378,124,1.11,0.37,0.105510,0.052755,0.158265,2.906519
121,Pascal Struijk,Leeds,DEF,4.3,78,2,3.1,0.5,0,1,...,167,63,267,98,1.00,0.17,0.000000,0.041513,0.041513,2.890667
139,Michael Kayode,Brentford,DEF,4.5,72,-1,2.7,0.7,0,1,...,233,92,222,85,1.03,0.23,0.000000,0.038168,0.038168,2.882000
77,Joachim Andersen,Fulham,DEF,4.5,93,0,3.6,4.7,0,1,...,106,36,76,24,1.02,0.20,0.000000,0.039284,0.039284,2.800111
296,Randal Kolo Muani,Spurs,FWD,6.9,36,1,1.8,0.4,1,0,...,375,45,284,45,1.10,0.24,0.078740,0.000000,0.078740,2.794000
285,Will Hughes,Crystal Palace,MID,4.7,38,1,1.5,0.1,0,1,...,407,179,467,160,1.03,0.37,0.000000,0.073650,0.073650,2.715556
327,Justin Devenny,Crystal Palace,MID,4.3,29,0,1.6,1.3,1,0,...,386,167,169,59,0.76,0.15,0.151771,0.000000,0.151771,2.701444
288,Anthony Elanga,Newcastle,MID,6.5,37,1,1.5,2.6,0,1,...,416,185,116,37,0.94,0.17,0.000000,0.085878,0.085878,2.678222

In [102]:
df['underperformance_and_form_index'] = df['underperformance_index'] + df['form']

In [103]:
df['underperformance_and_form_and_ppg_index'] = df['underperformance_and_form_index'] + df['points_per_game']

In [104]:
df_top_ofensivos = df.query('underperformance_index != inf and underperformance_index > 1').sort_values(['underperformance_and_form_and_ppg_index'], ascending = False)

In [105]:
df_top_ofensivos

,player_name,club_name,position_name,now_cost,total_points,event_points,points_per_game,selected_by_percent,goals_scored,assists,...,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,goals_per_90,assists_per_90,goal_involvements_per_90,underperformance_index,underperformance_and_form_index,underperformance_and_form_and_ppg_index
38,Ibrahima Konaté,Liverpool,DEF,5.5,109,1,4.0,4.2,1,0,...,84,28,1.04,0.35,0.038693,0.000000,0.038693,1.809111,7.409111,11.409111
79,Viktor Gyökeres,Arsenal,FWD,8.8,93,2,3.4,12.3,10,0,...,27,5,1.10,0.50,0.499722,0.000000,0.499722,1.000556,7.000556,10.400556
272,Rayan Aït-Nouri,Man City,DEF,5.7,39,11,3.5,4.1,0,1,...,85,29,1.12,0.42,0.000000,0.139969,0.139969,1.571778,6.771778,10.271778
25,Elliot Anderson,Nott'm Forest,MID,5.4,119,1,4.2,6.3,1,3,...,60,20,1.01,0.25,0.035914,0.107741,0.143655,1.322611,5.722611,9.922611
30,Morgan Gibbs-White,Nott'm Forest,MID,7.3,114,9,4.1,3.4,7,2,...,99,32,1.02,0.26,0.263819,0.075377,0.339196,1.002370,5.802370,9.902370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,Tom Cairney,Fulham,MID,4.8,25,0,1.4,0.0,1,0,...,636,250,0.57,0.00,0.190275,0.000000,0.190275,1.261333,1.661333,3.061333
407,Marc Marc Guiu,Chelsea,FWD,4.1,12,0,1.3,5.8,0,1,...,63,12,0.36,0.00,0.000000,0.364372,0.364372,1.756444,1.756444,3.056444
352,Eddie Nketiah,Crystal Palace,FWD,5.4,23,0,1.9,0.3,2,0,...,318,53,0.43,0.00,0.434783,0.000000,0.434783,1.104000,1.104000,3.004000
391,Dilane Bakwa,Nott'm Forest,MID,5.9,14,1,1.4,0.0,0,1,...,678,274,0.79,0.00,0.000000,0.263158,0.263158,1.178000,1.578000,2.978000
342,Sávio Savinho,Man City,MID,6.9,26,0,1.6,0.4,0,2,...,279,99,0.81,0.33,0.000000,0.325497,0.325497,1.228889,1.228889,2.828889

In [106]:
df.query('minutes > 450').sort_values('minutes')[['player_name', 'minutes']]

             player_name  minutes
437  Benoît B.Badiashile      470
349          Tom Cairney      473
348        Jamie Gittens      486
339           Nathan Aké      487
376   Harrison Armstrong      491
..                   ...      ...
89        Đorđe Petrović     2520
31        Dean Henderson     2520
32       Jordan Pickford     2520
35           Robin Roefs     2520
29            David Raya     2610

[365 rows x 2 columns]

In [107]:
df.query('minutes > 450').sort_values(['defensive_contribution_per_90'], ascending = False)[['player_name', 'defensive_contribution_per_90']]

                      player_name  defensive_contribution_per_90
281                    Lewis Cook                          14.79
319                 Manuel Ugarte                          14.68
25                Elliot Anderson                          14.04
188                  Mats Wieffer                          13.64
172  Florentino Ibrain Florentino                          13.54
..                            ...                            ...
32                Jordan Pickford                           0.00
29                     David Raya                           0.00
35                    Robin Roefs                           0.00
414                Aaron Ramsdale                           0.00
415                Altay Bayindir                           0.00

[365 rows x 2 columns]

In [108]:
df['underperformance_defensive_index'] = df['defensive_contribution_per_90'] / (df['clean_sheets_per_90'] * 90)

In [109]:
df.query('minutes > 450').sort_values(['underperformance_defensive_index'], ascending = False)

,player_name,club_name,position_name,now_cost,total_points,event_points,points_per_game,selected_by_percent,goals_scored,assists,...,selected_rank_type,starts_per_90,clean_sheets_per_90,goals_per_90,assists_per_90,goal_involvements_per_90,underperformance_index,underperformance_and_form_index,underperformance_and_form_and_ppg_index,underperformance_defensive_index
437,Benoît B.Badiashile,Chelsea,DEF,4.4,7,0,0.9,0.0,0,0,...,224,1.15,0.00,0.0000,0.000000,0.000000,inf,inf,inf,inf
421,Issa Diop,Fulham,DEF,4.3,11,1,1.2,0.1,0,0,...,188,0.90,0.00,0.0000,0.000000,0.000000,inf,inf,inf,inf
389,Destiny Udogie,Spurs,DEF,4.3,15,0,1.2,0.3,0,1,...,117,0.91,0.00,0.0000,0.113350,0.113350,0.705778,0.905778,2.105778,inf
336,Rodrigo R.Gomes,Wolves,DEF,4.4,27,7,2.1,0.1,2,0,...,200,0.94,0.00,0.3125,0.000000,0.312500,0.864000,2.864000,4.964000,inf
331,Timothy Castagne,Fulham,DEF,4.3,29,0,1.4,0.1,0,1,...,168,0.97,0.00,0.0000,0.080501,0.080501,1.490667,2.290667,3.690667,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,David Raya,Arsenal,GKP,6.0,115,3,4.0,34.2,0,0,...,1,1.00,0.45,0.0000,0.000000,0.000000,NaN,NaN,NaN,0.0
221,Alphonse Areola,West Ham,GKP,4.3,51,0,2.5,2.1,0,1,...,18,1.00,0.00,0.0000,0.050000,0.050000,0.000000,0.000000,2.500000,NaN
360,Sam Johnstone,Wolves,GKP,4.4,21,0,1.8,0.1,0,0,...,64,1.00,0.00,0.0000,0.000000,0.000000,NaN,NaN,NaN,NaN
414,Aaron Ramsdale,Newcastle,GKP,4.8,11,0,1.6,0.7,0,0,...,29,0.98,0.00,0.0000,0.000000,0.000000,NaN,NaN,NaN,NaN
415,Altay Bayindir,Man Utd,GKP,4.7,11,0,1.8,0.3,0,0,...,41,1.00,0.00,0.0000,0.000000,0.000000,inf,inf,inf,NaN

In [110]:
df['underperformance_and_form_defensive_index'] = df['underperformance_defensive_index'] + df['form']

In [111]:
df['underperformance_and_form_and_ppg_defensive_index'] = df['underperformance_and_form_defensive_index'] + df['points_per_game']

In [114]:
df.query('underperformance_defensive_index != inf and underperformance_defensive_index > 1 and form > 1').sort_values(['underperformance_and_form_and_ppg_defensive_index'], ascending = False)

,player_name,club_name,position_name,now_cost,total_points,event_points,points_per_game,selected_by_percent,goals_scored,assists,...,clean_sheets_per_90,goals_per_90,assists_per_90,goal_involvements_per_90,underperformance_index,underperformance_and_form_index,underperformance_and_form_and_ppg_index,underperformance_defensive_index,underperformance_and_form_defensive_index,underperformance_and_form_and_ppg_defensive_index
180,André André,Wolves,MID,5.2,63,5,2.4,0.1,0,0,...,0.09,0.0,0.000000,0.000000,inf,inf,inf,1.538272,3.538272,5.938272
308,Bashir Humphreys,Burnley,DEF,3.9,33,1,2.8,0.1,0,2,...,0.09,0.0,0.185759,0.185759,0.376833,2.376833,5.176833,1.043210,3.043210,5.843210
197,Maxime Estève,Burnley,DEF,3.9,59,0,2.4,7.8,0,0,...,0.08,0.0,0.000000,0.000000,inf,inf,inf,1.372222,3.172222,5.572222
281,Lewis Cook,Bournemouth,MID,4.9,38,0,2.4,0.0,0,1,...,0.10,0.0,0.103448,0.103448,0.580000,1.780000,4.180000,1.643333,2.843333,5.243333
333,Toti Toti,Wolves,DEF,4.2,28,8,2.0,0.1,0,0,...,0.09,0.0,0.000000,0.000000,inf,inf,inf,1.027160,2.627160,4.627160
325,Andrey Andrey Santos,Chelsea,MID,4.5,30,2,1.4,0.3,0,0,...,0.09,0.0,0.000000,0.000000,inf,inf,inf,1.193827,3.193827,4.593827